export const ERROR_MESSAGES = {
  DB_OPERATION_ERROR: "Database error occurred during operation.",
  USER_NOT_FOUND: "User not found.",
  USER_CREATION_FAILED: "Failed to create user.",
  COMPANY_NOT_FOUND: "Company not found.",
  TOO_MANY_COMPANIES_FOUND: "Too many companies found.",
  COMPANY_CREATION_ERROR: "Error occurred while creating company.",
  EVENT_TYPE_NOT_FOUND: "EventType not found.",
  ALL_EVENT_TYPES_EXIST: "All event types already exist.",
  EVENT_TYPES_ADDED_SUCCESS: "Successfully added new event types.",
  ALL_ACTIVITY_TYPES_EXIST: "All activity types already exist.",
  ACTIVITY_TYPES_ADDED_SUCCESS: "Successfully added new activity types.",
  ACCOUNT_NOT_FOUND: "Account not found.",
  ACCOUNT_CREATION_FAILED: "Failed to create account.",
  LOGIN_FAILED: "Login failed.",
  MISSING_REQUIRED_FIELDS: "Missing required fields.",
  TYPE_MAPPING_CREATION_FAILED: "Failed to create type mapping.",
  TYPE_MAPPING_UPDATE_FAILED: "Failed to update type mapping.",
  CALENDLY_EVENT_UPDATE_FAILED: "Calendly Event not found.",
  CALENDLY_EVENT_NOT_FOUND: "Failed to update calendly event.",
  PIPEDRIVE_ACTIVITY_UPDATE_FAILED: "Failed to update pipedrive activity.",
  PIPEDRIVE_ACTIVITY_CREATION_FAILED: "Failed to pipedrive activity in DB.",
  CALENDLY_EVENT_CREATION_FAILED: "Failed to calendly event in DB.",
  PIPEDRIVE_PERSON_CREATION_FAILED: "Failed to pipedrive person in DB.",
  PIPEDRIVE_PERSON_NOT_FOUND: "Pipedrive person not found.",
  PIPEDRIVE_DEAL_CREATION_FAILED: "Failed to pipedrive person in DB.",
  PIPEDRIVE_DEAL_NOT_FOUND: "Pipedrive deal not found.",
  PIPEDRIVE_ACTIVITY_TYPE_NOT_FOUND: "Pipedrive activity type not found.",
  PIPEDRIVE_ACTIVITY_NOT_FOUND: "Pipedrive activity not found.",
};
