import SetupFrame from "@/components/SetupFrame";
import { SettingsDataRes } from "../api/v1/settings-modal/route";

const settingsData: SettingsDataRes = {
  data: {
    calendlyEventTypes: {
      collection: [
        {
          uri: "https://api.calendly.com/event_types/ABCD1234",
          name: "Initial Consultation",
          active: true,
          booking_method: "instant",
          slug: "initial-consultation",
          scheduling_url: "https://calendly.com/user/initial-consultation",
          duration: 30,
          duration_options: [15, 30, 60],
          kind: "solo",
          pooling_type: "round_robin",
          type: "standard",
          color: "#4499FF",
          created_at: "2024-01-15T10:00:00Z",
          updated_at: "2024-01-15T10:00:00Z",
          internal_note: "Internal notes for the meeting",
          description_plain: "30-minute initial consultation call",
          description_html: "<p>30-minute initial consultation call</p>",
          profile: {
            type: "user",
            name: "John Doe",
            owner: "john.doe@example.com",
          },
          secret: false,
          deleted_at: null,
          admin_managed: false,
          locations: [
            {
              kind: "phone",
              phone_number: 1234567890,
              additional_info: "Please provide your preferred phone number",
            },
          ],
          position: 0,
          custom_questions: [
            {
              name: "What is your company size?",
              type: "single_select",
              position: 0,
              enabled: true,
              required: true,
              answer_choices: ["1-10", "11-50", "51-200", "201+"],
              include_other: false,
            },
            {
              name: "Additional Notes",
              type: "text",
              position: 1,
              enabled: true,
              required: false,
              answer_choices: [],
              include_other: false,
            },
          ],
        },
        {
          uri: "https://api.calendly.com/event_types/EFGH5678",
          name: "Follow-up Meeting",
          active: true,
          booking_method: "instant",
          slug: "follow-up-meeting",
          scheduling_url: "https://calendly.com/user/follow-up-meeting",
          duration: 45,
          duration_options: [30, 45, 60],
          kind: "solo",
          pooling_type: "round_robin",
          type: "standard",
          color: "#FF6B6B",
          created_at: "2024-01-16T10:00:00Z",
          updated_at: "2024-01-16T10:00:00Z",
          internal_note: "Follow-up discussion",
          description_plain: "45-minute follow-up meeting",
          description_html: "<p>45-minute follow-up meeting</p>",
          profile: {
            type: "user",
            name: "John Doe",
            owner: "john.doe@example.com",
          },
          secret: false,
          deleted_at: null,
          admin_managed: false,
          locations: [
            {
              kind: "google_meet",
              phone_number: null,
              additional_info: "Google Meet link will be provided",
            },
          ],
          position: 1,
          custom_questions: [],
        },
        {
          uri: "https://api.calendly.com/event_types/IJKL9012",
          name: "Product Demo",
          active: true,
          booking_method: "instant",
          slug: "product-demo",
          scheduling_url: "https://calendly.com/user/product-demo",
          duration: 60,
          duration_options: [60],
          kind: "solo",
          pooling_type: "round_robin",
          type: "standard",
          color: "#4CAF50",
          created_at: "2024-01-17T10:00:00Z",
          updated_at: "2024-01-17T10:00:00Z",
          internal_note: "Product demonstration session",
          description_plain: "1-hour product demonstration",
          description_html: "<p>1-hour product demonstration</p>",
          profile: {
            type: "user",
            name: "John Doe",
            owner: "john.doe@example.com",
          },
          secret: false,
          deleted_at: null,
          admin_managed: false,
          locations: [
            {
              kind: "zoom",
              phone_number: null,
              additional_info: "Zoom link will be provided",
            },
          ],
          position: 2,
          custom_questions: [
            {
              name: "What features are you most interested in?",
              type: "text",
              position: 0,
              enabled: true,
              required: true,
              answer_choices: [],
              include_other: false,
            },
          ],
        },
        {
          uri: "https://api.calendly.com/event_types/MNOP3456",
          name: "Technical Support",
          active: true,
          booking_method: "instant",
          slug: "technical-support",
          scheduling_url: "https://calendly.com/user/technical-support",
          duration: 30,
          duration_options: [15, 30],
          kind: "solo",
          pooling_type: "round_robin",
          type: "standard",
          color: "#9C27B0",
          created_at: "2024-01-18T10:00:00Z",
          updated_at: "2024-01-18T10:00:00Z",
          internal_note: "Technical support session",
          description_plain: "30-minute technical support call",
          description_html: "<p>30-minute technical support call</p>",
          profile: {
            type: "user",
            name: "John Doe",
            owner: "john.doe@example.com",
          },
          secret: false,
          deleted_at: null,
          admin_managed: false,
          locations: [
            {
              kind: "microsoft_teams",
              phone_number: null,
              additional_info: "Teams link will be provided",
            },
          ],
          position: 3,
          custom_questions: [
            {
              name: "Please describe your technical issue",
              type: "text",
              position: 0,
              enabled: true,
              required: true,
              answer_choices: [],
              include_other: false,
            },
          ],
        },
        {
          uri: "https://api.calendly.com/event_types/QRST7890",
          name: "Strategy Session",
          active: true,
          booking_method: "instant",
          slug: "strategy-session",
          scheduling_url: "https://calendly.com/user/strategy-session",
          duration: 90,
          duration_options: [60, 90, 120],
          kind: "solo",
          pooling_type: "round_robin",
          type: "standard",
          color: "#FF9800",
          created_at: "2024-01-19T10:00:00Z",
          updated_at: "2024-01-19T10:00:00Z",
          internal_note: "Strategic planning session",
          description_plain: "90-minute strategy session",
          description_html: "<p>90-minute strategy session</p>",
          profile: {
            type: "user",
            name: "John Doe",
            owner: "john.doe@example.com",
          },
          secret: false,
          deleted_at: null,
          admin_managed: false,
          locations: [
            {
              kind: "zoom",
              phone_number: null,
              additional_info: "Zoom link will be provided",
            },
          ],
          position: 4,
          custom_questions: [
            {
              name: "What are your main business goals?",
              type: "text",
              position: 0,
              enabled: true,
              required: true,
              answer_choices: [],
              include_other: false,
            },
          ],
        },
      ],
      pagination: {
        count: 5,
        next_page: "",
        previous_page: "",
        next_page_token: "",
        previous_page_token: "",
      },
    },
    pipedriveAcitvityTypes: [
      {
        id: 1,
        order_nr: 1,
        name: "Call",
        key_string: "call",
        icon_key: "phone",
        active_flag: true,
        color: "#44BB77",
        is_custom_flag: false,
        add_time: "2024-01-15T10:00:00Z",
        update_time: "2024-01-15T10:00:00Z",
      },
      {
        id: 2,
        order_nr: 2,
        name: "Meeting",
        key_string: "meeting",
        icon_key: "meeting",
        active_flag: true,
        color: "#FF7F50",
        is_custom_flag: false,
        add_time: "2024-01-15T10:00:00Z",
        update_time: "2024-01-15T10:00:00Z",
      },
      {
        id: 3,
        order_nr: 3,
        name: "Email",
        key_string: "email",
        icon_key: "mail",
        active_flag: true,
        color: "#2196F3",
        is_custom_flag: false,
        add_time: "2024-01-15T10:00:00Z",
        update_time: "2024-01-15T10:00:00Z",
      },
      {
        id: 4,
        order_nr: 4,
        name: "Task",
        key_string: "task",
        icon_key: "task",
        active_flag: true,
        color: "#9C27B0",
        is_custom_flag: false,
        add_time: "2024-01-15T10:00:00Z",
        update_time: "2024-01-15T10:00:00Z",
      },
      {
        id: 5,
        order_nr: 5,
        name: "Deadline",
        key_string: "deadline",
        icon_key: "clock",
        active_flag: true,
        color: "#F44336",
        is_custom_flag: false,
        add_time: "2024-01-15T10:00:00Z",
        update_time: "2024-01-15T10:00:00Z",
      },
      {
        id: 6,
        order_nr: 6,
        name: "Follow-up",
        key_string: "follow_up",
        icon_key: "redo",
        active_flag: true,
        color: "#FF9800",
        is_custom_flag: true,
        add_time: "2024-01-15T10:00:00Z",
        update_time: "2024-01-15T10:00:00Z",
      },
      {
        id: 7,
        order_nr: 7,
        name: "Demo",
        key_string: "demo",
        icon_key: "presentation",
        active_flag: true,
        color: "#4CAF50",
        is_custom_flag: true,
        add_time: "2024-01-15T10:00:00Z",
        update_time: "2024-01-15T10:00:00Z",
      },
    ],
  },
};

const TestPage = () => {
  return (
    <div className="bg-background text-foreground">
      <SetupFrame settingsData={settingsData} />
    </div>
  );
};

export default TestPage;
